### ISSUE TITLE
IMAP: Headers never updated

### ISSUE THREAD

**Issue by mook-as** [mailprocessing/mailprocessing#2]
As far as I can tell, if `--interval` is used to re-process folders as new mail comes in, nothing ever calls `_cache_headers()` in `__iter__()`; this means it just sorts the same messages over and over, instead of actually processing new mail.

This can be see in the logs:
```
Dec 29 14:53:15 localhost imapproc[17242]: ==> Moving UID 633 to Lists/moo
Dec 29 14:53:15 localhost imapproc[17242]: ==> Copying 633 to Lists/moo
Dec 29 14:53:15 localhost imapproc[17242]: ==> Deleting 633
Dec 29 14:53:20 localhost imapproc[17242]: ==> Moving UID 633 to Lists/moo
Dec 29 14:53:20 localhost imapproc[17242]: ==> Copying 633 to Lists/moo
Dec 29 14:53:20 localhost imapproc[17242]: ==> Deleting 633
Dec 29 14:53:25 localhost imapproc[17242]: ==> Moving UID 633 to Lists/moo
Dec 29 14:53:25 localhost imapproc[17242]: ==> Copying 633 to Lists/moo
Dec 29 14:53:25 localhost imapproc[17242]: ==> Deleting 633
Dec 29 14:53:30 localhost imapproc[17242]: ==> Moving UID 633 to Lists/moo
```

The same message keeps getting moved every time the interval happens.

**Comment by jgrassler** [comment]
Sorry, for the late reply, I missed this one (I had notifications turned off for this repository...). It's indeed only called in the constructor, which causes the behaviour you describe.

**Comment by jgrassler** [comment]
I fixed this in `master`. Can you test and confirm it works for you (I don't use continuous mode myself, I prefer running `imapproc` through `cron`)?

**Comment by mook-as** [comment]
Thank you, the fix appears to work for me.  I'll look into switching to using cron (well, systemd timer jobs) as well, just to avoid less tested code paths.
